### ISSUE TITLE
TCP Client

### ISSUE THREAD

**Issue by heX16** [njh/EtherSia#11]
I understand correctly? - Is there no TCP client in this library?

**Comment by alexandrecuer** [comment]
There is one but not working perfectly...it is very hard to have it working with so little memory...I only implemented active open and passive close....the code is UIP flavored (ie Adam Dunkel initial TCP stack dedicated to small memory systems), but the resending algorithm is not perfect (resending too much)

you can check this link : https://github.com/alexandrecuer/EtherSia

There is one example with data sending to an emonCMS server on a local lan
http://files.openenergymonitor.org/emonSD-07Nov16.zip
https://github.com/openenergymonitor/emonpi/wiki/emonSD-pre-built-SD-card-Download-&-Change-Log 

The code in TCPClient.h and cpp is documented are but I have some pdf synth files also....if usefull ask I will provide...

Alex

**Comment by njh** [comment]
I keep meaning to spend some more time on EtherSia and get the TCP client code finished off... hopefully soon.

Packet/datagram (such as UDP/ICMP) based protocols aren't too bad to implement on an Arduino Uno.
But I have found that the the limited resources (particularly 2kB of RAM), do make TCP tricky to implement well/while being easy to use.

**Comment by heX16** [comment]
@alexandrecuer thank for links!


> Packet/datagram (such as UDP/ICMP) based protocols aren't too bad to implement on an Arduino Uno.

I agree. I use only UDP. But I had to ask about TCP Client. I think it is worth to clarify this detail in the description.
P.S. By the way, the commit with  [Multicast ](https://github.com/njh/EtherSia/pull/10) is not merged because it has problems in the code or just "waiting for its time"? (I'm interested because I plan to use a multicast)

**Comment by njh** [comment]
Clarified that there is no TCP Client support in 66a33abddff2e74395fde098c688744c152ac0b4
