### ISSUE TITLE
When using lwIP_enc28j60 the Wifi doesn't work

### ISSUE THREAD

**Issue by tiagorosolen** [njh/EtherSia#16]
Hallo Nicholas!

I'm writing to you thinking that you're the author of the lwIP_enc28j60 currently build in the Arduino Environment. If that's not the case, please disregard and delete the issue (unless you have a way of helping me, in which I'll be very thankful)

The problem is that WiFi does not work when ethernet is initialized.

I have already another issue added to the ESP8266 repository with all the details: [esp Issue](https://github.com/esp8266/Arduino/issues/8697)

Thank you in advanced Nicholas and thank you a million for the library. It's so much better than the old UIPEthernet that I cant' describe.

Kudos
Tiago

**Comment by njh** [comment]
Sorry, I missed this.

I'm afraid I have nothing to do with lwIP_enc28j60.
